### ISSUE TITLE
Error while dumping psx emulated game

### ISSUE THREAD

**Issue by kiletic** [kekeimiku/PointerSearcher-X#17]
I ran the following command `sudo ./ptrsx-dumper disk -p 15853` where 15853 is the PID of the [pcsxr](https://github.com/mirror/pcsxr) emulator running tekken 3 and I got the following error:

![image](https://github.com/kekeimiku/PointerSearcher-X/assets/55144452/e9724bd0-1a74-42c1-a570-87a955c1c936)

After that pcsxr-15853.dump file was created but it was empty. Any help?

**Comment by kekeimiku** [comment]
I just released a new version which should fix this issue. 
https://github.com/kekeimiku/PointerSearcher-X/releases/tag/v0.3.0

**Comment by kiletic** [comment]
Now I'm getting a different error, do you know what could be the issue? Like before the dump file is created but it is empty.

![image](https://github.com/kekeimiku/PointerSearcher-X/assets/55144452/9d24af36-a260-4011-a23a-8e9ceb59d13b)

**Comment by kekeimiku** [comment]
> Now I'm getting a different error, do you know what could be the issue? Like before the dump file is created but it is empty.
> 
> ![image](https://user-images.githubusercontent.com/55144452/265449129-9d24af36-a260-4011-a23a-8e9ceb59d13b.png)
> 
> EDIT: I'm getting this error even when dumping memory of a program that worked before (something other than pcsxr).

Which operating system do you use?

**Comment by kiletic** [comment]
Sorry I forgot to include this information in the first post - it is Linux, namely Ubuntu 23.04

**Comment by kekeimiku** [comment]
> Sorry I forgot to include this information in the first post - it is Linux, namely Ubuntu 23.04

Sorry I just released a new version and it should have been fixed. XD 

https://github.com/kekeimiku/PointerSearcher-X/releases/tag/v0.3.1

**Comment by kekeimiku** [comment]
> Now I'm getting a different error, do you know what could be the issue? Like before the dump file is created but it is empty.
> 
> ![image](https://user-images.githubusercontent.com/55144452/265449129-9d24af36-a260-4011-a23a-8e9ceb59d13b.png)
> 
> EDIT: I'm getting this error even when dumping memory of a program that worked before (something other than pcsxr).

I just released a new version and it should have been fixed. XD

**Comment by kiletic** [comment]
It is indeed fixed, thanks!
