### ISSUE TITLE
Cannot inject WeChat process

### ISSUE THREAD

**Issue by paulzhn** [kekeimiku/PointerSearcher-X#20]
It occurs `Error: OpenProcess(5)`.

The command is 
```
./ptrsx-dumper test --pid $(pgrep WeChat |head -1) --path "WeChat+0x4C58BC0->0->8->8->16->32->8->8->64->8->0->0" -n 32
```

I'm using a MacBook pro with m1 pro, and the system version is 13.4.1. The wechat version is 3.8.3(27318).

**Comment by paulzhn** [comment]
Solved, injecting WeChat needs to close SIP.

**Comment by kekeimiku** [comment]
Try to re-sign WeChat. command `sudo codesign --sign - --force --deep /Applications/WeChat.app`
