### ISSUE TITLE
"Unrecognized argument: -t" 

### ISSUE THREAD

**Issue by arft1kwerg** [kekeimiku/PointerSearcher-X#27]
Version 0.7.0
asset: ptrsx-x86_64-unknown-linux-gnu.zip
os: ubuntu

Running the scanner returns "Unrecognized argument: -t" or "--target". Reverting to 0.6.1 allows the command to run. Can't find any mention of this change in available documentation.

![image](https://github.com/kekeimiku/PointerSearcher-X/assets/29517963/a333bc6c-03f1-4ac8-b613-1f8fd49b87c8)

**Comment by kekeimiku** [comment]
I forgot about this, the target is now changed to `list/l` and multiple addresses can be specified.

**Comment by arft1kwerg** [comment]
> I forgot about this, the `--target/-t` is now changed to `--list/-l` and multiple addresses can be specified.

Ah, that makes sense considering the multiple address support. Thanks for the response.
